#!/usr/bin/env ruby

# Trap ^C
Signal.trap("INT") {
  puts "\nCtrl-C detected. Exiting..."
  sleep 1
  exit
}

$:.unshift(File.expand_path("../../lib", __FILE__))
require "status-page"
require "status_page/cli"

StatusPage::CLI.start(ARGV)
